# Site settings
title: "B.Kerler's Reversing Cave"
email: info@revskills.de
description: "Just another reversing blog."
baseurl: ""
url: "https://bkerler.github.io/"
title_description: ""
title_image: "https://avatars2.githubusercontent.com/u/6317772?s=40"
google_analytics: "UA-138861602-1"
disqus_account: bkerler
github_repository: https://github.com/bkerler
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: viperbjk
github_username:  bkerler
instagram_username: 
reddit_username: 
linkedin_link: 
google_plus_link: 
stackoverflow_link:
xing_link:
facebook_link:

# Footer
footer_left: ""
footer_right: ""

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
